<?php 

function arg_utilizator_user_presave(&$edit, $account, $category){
	$cont_nr = $edit['tip_cont']['und'][0]['value'];
	global $user;
	switch ($cont_nr) {
		case 0:
			$role = user_role_load_by_name('Student');
			$role_id = $role->rid;
			break;
		
		case 1:
			$role = user_role_load_by_name('Profesor');
			$role_id = $role->rid;
			break;
		
		case 2:
			$role = user_role_load_by_name('Companie');
			$role_id = $role->rid;
			break;
		
	}
	dsm($role);
//	dsm($role_id);
	$new_user_roles = array(
			DRUPAL_AUTHENTICATED_RID => 'authenticated user',
			$role_id => $role->name,
	);
//	dsm($account);
//	dsm($edit);
//	dsm($category);
//	dsm($user);
	
	$edit['roles'] = $new_user_roles;
	//user_save($account);
	//test
}