<?php

function arg_aplicatie_node_info() {
  return array(
      'arg_aplicatie' => array(
          'name' => t('aplicatie'),
          'base' => 'arg_aplicatie',
          'description' => t('Folositi acest tip de continut pentru a crea o aplicatie noua.'),
          'has_title' => TRUE,
          'title_label' => 'Numele Aplicatiei',
          'help' => t('Introduceti numele vostru si scrisoarea de intentie.'),
          ),
      );

}
function arg_aplicatie_form($node, $form_state){

  return node_content_form($node, $form_state);
  
}

function arg_aplicatie_form_alter(&$form, &$form_state,$form_id){
	if($_GET['nid-bursa'] && $form_id == 'arg_bursa_node_form'){
		$form['bursa']['und'][0]['value']['#default_value'] = $_GET['nid-bursa'];
	}
}