<?php

function arg_aplicatie_node_info() {
  return array(
      'arg_aplicatie' => array(
          'name' => t('Aplicatie'),
          'base' => 'arg_aplicatie',
          'description' => t('Folositi acest tip de continut pentru a crea o aplicatie noua.'),
          'has_title' => TRUE,
          'title_label' => 'Numele Aplicatiei',
          'help' => t('Introduceti numele vostru si scrisoarea de intentie.'),
          ),
      );

}
function arg_aplicatie_form($node, $form_state){

  return node_content_form($node, $form_state);
  
}

function arg_aplicatie_form_alter(&$form, &$form_state,$form_id){
	$form['referinta_sesiune']['#access']=false;
	
	if($_GET['nid-sesiune'] && $form_id == 'arg_aplicatie_node_form'){
 		$form['referinta_sesiune']['und'][0]['value']['#default_value'] = $_GET['nid-sesiune'];
 	}
}

function arg_aplicatie_arg_core_referinta_univ($nid, $type, $node){

	$nod_bursa = node_load($node['entity']->referinta_sesiune['und'][0]['value']);
	$output = l($nod_bursa->title, 'node/' . $nod_bursa->nid);
	return $output;
}

function arg_aplicatie_permission(){
	return array(
			'adauga aplicatie' => array(
					'title' => 'Adauga aplicatie',
					'description' => 'Ofera posibilitatea de a adauga o aplicatie'
					),
			'update aplicatie' => array(
					'title' => 'Update aplicatie',
					'description' => 'Ofera posibilitatea de a edita o aplicatie'
					),
			'delete aplicatie' => array(
					'title' => 'Delete aplicatie',
					'description' => 'Ofera posibilitatea de a sterge o aplicatie'
					),
			'view aplicatie' => array(
					'title' => 'View aplicatie',
					'description' => 'Ofera posibilitatea de a vedea o aplicatie'
					),
			);
}

function arg_aplicatie_node_access($node, $op, $account){
	$type = is_string($node) ? $node : $node->type;
	if($type == 'arg_aplicatie'){
		switch ($op){
			case 'create':
				if(user_access('adauga aplicatie',$account)){
					return NODE_ACCESS_ALLOW;
				}
			case 'update':
				if(user_access('update aplicatie',$account)){
					if($node->uid == $account->uid){
						return NODE_ACCESS_ALLOW;
					}
				}
			case 'delete':
				if(user_access('delete aplicatie',$account)){
					return NODE_ACCESS_ALLOW;
				}
			case 'view':
				if($node->uid == $account->uid){
					return NODE_ACCESS_ALLOW;
				} else if (user_access('view aplicatie',$account)) {
					return NODE_ACCESS_IGNORE;
				} else {
					return NODE_ACCESS_DENY;
				}
		}
	}
}