<?php


function arg_universitate_install() {


  $t = get_t();
  node_types_rebuild();
  $fields = array();
  $fields = _arg_core_installed_fields();
  foreach($fields as $field){

    field_create_field($field);
  }
  $instances = array();
  $instances = _arg_core_installed_instances();
  foreach ($instances as $instance) {
    $instance['entity_type'] = 'node';
    $instance['bundle'] = 'arg_universitate';
    field_create_instance($instance);
    }
  }





