<?php 

function arg_sesiune_node_info() {
	return array(
			'arg_sesiune' => array(
					'name' => t('Sesiune'),
					'base' => 'arg_sesiune',
					'description' => t('Folositi acest tip de continut pentru a adauga o sesiune noua.'),
					'has_title' => TRUE,
					'title_label' => 'Sesiune',
					'help' => t('Introduceti perioada de desfasurare a sesiunii.'),
			),
	);

}
function arg_sesiune_form($node, $form_state){

	return node_content_form($node, $form_state);

}

function arg_sesiune_form_alter(&$form, &$form_state,$form_id){
	if($_GET['nid-bursa'] && $form_id == 'arg_sesiune_node_form'){
		$form['bursa']['und'][0]['value']['#default_value'] = $_GET['nid-bursa'];
	}
}

function arg_sesiune_arg_core_butoane($nid,$type,$node){
	if($type == 'arg_sesiune'){
		$options['query'] = array(
				'nid-sesiune' => $node['entity']->nid,
			);
			$output = l('Aplica','node/add/arg-aplicatie',$options);
		return $output;
	}

}

function arg_sesiune_permission(){
	return array(
			'adauga sesiune' => array(
					'title' => 'Adauga sesiune',
					'description' => 'Ofera posibilitatea de a adauga o sesiune'
					),
			'update sesiune' => array(
					'title' => 'Update sesiune',
					'description' => 'Ofera posibilitatea de a edita o sesiune'
					),
			'delete sesiune' => array(
					'title' => 'Delete sesiune',
					'description' => 'Ofera posibilitatea de a sterge o  sesiune'
					),
			);
}

function arg_sesiune_node_access($node, $op, $account){
	switch ($op){
		case 'create':
			if(user_access('adauga sesiune',$account)){
				return NODE_ACCESS_ALLOW;
			}
		case 'update':
			if(user_access('update sesiune',$account)){
				return NODE_ACCESS_ALLOW;
			}
		case 'delete':
			if(user_access('delete sesiune',$account)){
				return NODE_ACCESS_ALLOW;
			}
	}
}