<?php

function arg_bursa_node_info() {
  return array(
      'arg_bursa' => array(
          'name' => t('Bursa'),
          'base' => 'arg_bursa',
          'description' => t('Folositi acest tip de continut pentru a crea o Bursa noua.'),
          'has_title' => TRUE,
          'title_label' => 'Numele Bursei',
          'help' => t('Introduceti numele Bursei,descrierea si conditiile de aplicare.'),
          ),
      );

}
function arg_bursa_form($node, $form_state){

  return node_content_form($node, $form_state);
  
}

function arg_bursa_form_alter(&$form, &$form_state,$form_id){
	
	if($_GET['nid-facultate'] && $form_id == 'arg_bursa_node_form'){
		$form['facultate']['und'][0]['value']['#default_value'] = $_GET['nid-facultate'];
		
	}
	if($_GET['nid-universitate'] && $form_id == 'arg_bursa_node_form'){
		$form['universitate']['und'][0]['value']['#default_value'] = $_GET['nid-universitate'];
		
	}
	$form['facultate']['#access'] = false;
	$form['universitate']['#access'] = false;
}

function arg_bursa_arg_core_butoane($nid,$type,$node){
	if($type == 'arg_bursa'){
		$options['query'] = array(
				'nid-bursa' => $node['entity']->nid,
		);
		$output = l('Deschide sesiune', 'node/add/arg-sesiune',$options);
		return $output;
	}
	
}

function arg_bursa_arg_core_referinta_univ($nid, $type, $node){

	$nod_universitate = node_load($node['entity']->universitate['und'][0]['value']);
	$output = l($nod_universitate->title, 'node/' . $nod_universitate->nid);
	return $output;
}

function arg_bursa_arg_core_referinta_fac($nid, $type, $node){
	$nod_facultate = node_load($node['entity']->facultate['und'][0]['value']);
	$output = l($nod_facultate->title, 'node/' . $nod_facultate->nid);
	return $output;
}

function arg_bursa_permission(){
	return array(
			'adauga bursa' => array(
					'title' => 'Adauga bursa',
					'description' => 'Ofera posibilitatea de a adauga o bursa'
					),
			'update bursa' => array(
					'title' => 'Update bursa',
					'description' => 'Ofera posibilitatea de a edita o bursa'
					),
			'delete bursa' => array(
					'title' => 'Delete bursa',
					'description' => 'Ofera posibilitatea de a sterge o  bursa'
					),
			);
}

function arg_bursa_node_access($node, $op, $account){
	switch ($op){
		case 'create':
			if(user_access('adauga bursa',$account)){
				return NODE_ACCESS_ALLOW;
			}
		case 'update':
			if(user_access('update bursa',$account)){
				return NODE_ACCESS_ALLOW;
			}
		case 'delete':
			if(user_access('delete bursa',$account)){
				return NODE_ACCESS_ALLOW;
			}
	}
}
