<?php

function arg_universitate_node_info() {
  return array(
      'arg_universitate' => array(
          'name' => t('Universitate'),
          'base' => 'arg_universitate',
          'description' => t('Folositi acest tip de continut pentru a crea o Universitate noua.'),
          'has_title' => TRUE,
          'title_label' => 'Numele Universitatii',
          'help' => t('Introduceti numele Universitatii,descrierea si datele de contact.'),
          ),
      );

}
function arg_universitate_form($node, $form_state){

	return node_content_form($node, $form_state);
	
}


function arg_universitate_arg_core_butoane($nid,$type,$node){
	if($type == 'arg_universitate'){
		$options['query'] = array('nid-universitate' => $node['entity']->nid);
		$output = l('Adauga Facultate', 'node/add/arg-facultate', $options);
		return $output;
	}
}

function arg_universitate_permission(){
	return array(
			'adauga universitate' => array(
					'title' => 'Adauga Universitate',
					'description' => 'Ofera posibilitatea de a adauga o universitate'
					),
			'update universitate' => array(
					'title' => 'Update Universitate',
					'description' => 'Ofera posibilitatea de a edita o universitate'
					),
			'delete universitate' => array(
					'title' => 'Delete Universitate',
					'description' => 'Ofera posibilitatea de a sterge o  universitate'
					),
			);
}

function arg_universitate_node_access($node, $op, $account){
	switch ($op){
		case 'create':
			if(user_access('adauga universitate',$account)){
				return NODE_ACCESS_ALLOW;
			}
		case 'update':
			if(user_access('update universitate',$account)){
				$query = "SELECT uid FROM {arg_utilizator_drepturi} WHERE uid=%d AND nid=%d AND drept='edit'";
				$result = db_result($query,$account->uid,$node->nid);
				if($result = $accout->uid){
					return NODE_ACCESS_ALLOW;
				}
			}
		case 'delete':
			if(user_access('delete universitate',$account)){
				return NODE_ACCESS_ALLOW;
			}
	}
}