<?php

function arg_universitate_node_info() {
  return array(
      'arg_universitate' => array(
          'name' => t('Universitate'),
          'base' => 'arg_universitate',
          'description' => t('Folositi acest tip de continut pentru a crea o Universitate noua.'),
          'has_title' => TRUE,
          'title_label' => 'Numele Universitatii',
          'help' => t('Introduceti numele Universitatii,descrierea si datele de contact.'),
          ),
      );

}
function arg_universitate_form($node, $form_state){

	return node_content_form($node, $form_state);
	
}


function arg_universitate_arg_core_butoane($nid,$type,$node){
	if($type == 'arg_universitate'){
		$options['query'] = array('nid-universitate' => $node['entity']->nid);
		$output = l('Adauga Facultate', 'node/add/arg-facultate', $options);
		return $output;
	}
}