<?php

function arg_facultate_node_info() {
  return array(
      'arg_facultate' => array(
          'name' => t('Facultate'),
          'base' => 'arg_facultate',
          'description' => t('Folositi acest tip de continut pentru a crea o Facultate noua.'),
          'has_title' => TRUE,
          'title_label' => 'Numele Facultatii',
          'help' => t('Introduceti numele Facultatii,descrierea si datele de contact.'),
          ),
      );

}
function arg_facultate_form($node, $form_state){
  
  return node_content_form($node, $form_state);

}

function arg_facultate_form_alter(&$form, &$form_state,$form_id){
  if($_GET['nid-universitate'] && $form_id == 'arg_facultate_node_form'){
  	$form['universitate_ref']['und'][0]['value']['#default_value'] = $_GET['nid-universitate'];
  }
}

