<?php

/**
 * Modulul acesta ofera un tip de nod denumit Facultate.
 */

/**
 * Implements hook_node_info().
 */

function arg_facultate_node_info() {
  return array(
      'arg_facultate' => array(
          'name' => t('Facultate'),
          'base' => 'arg_facultate',
          'description' => t('Folositi acest tip de continut pentru a crea o Facultate noua.'),
          'has_title' => TRUE,
          'title_label' => 'Numele Facultatii',
          'help' => t('Introduceti numele Facultatii,descrierea si datele de contact.'),
          ),
      );

}
function arg_facultate_form($node, $form_state){
  
  return node_content_form($node, $form_state);

}

function arg_facultate_form_alter(&$form, &$form_state,$form_id){
  dsm($form_id);
  //dsm($form);
  //dsm($form_state);
  dsm($form['referinta']['und'][0]['value']['#default_value']);
  
  if($_GET['nid-universitate'] && $form_id == 'arg_facultate_node_form'){
  	$form['referinta']['und'][0]['value']['#default_value'] = $_GET['nid-universitate'];
  }
  //$form['referinta']['#value'] = $_GET['nid-universitate'];
}

/*function arg_facultate_view($node, $view_mode) {
    $node = node_object_prepare($node);
    $node->content['pseudonim'] = array(
        '#markup' => '',
        );
    $node->content['culoare_fundal'] = array(
        '#markup' => '',
        );
    return $node;

  }*/